Repository adrgarcha/mariwano, pull requests merged in 2024-07, with the labels that each got.

#37 Subcomandos de /invertir y balancear /gamble
  src/commands/economy/daily.ts
  src/commands/economy/gamble.ts
  src/commands/fun/invertir.ts
Labels: improvement

#39 Arreglar permisos de los workflows para cambiar el token
  .github/workflows/switch-token.yml
Labels: bug

#40 Eliminar el workflow 'switch-token' y cambiar el token a produccion
  .github/workflows/switch-token.yml
  src/index.ts
Labels: bug

#42 Hacer que siempre se registren todos los comandos
  src/index.ts
Labels: bug

#45 Manejador de comandos y eventos
  Dockerfile
  package-lock.json
  package.json
  src/commands/admin/autorole-configure.ts
  src/commands/admin/autorole-diable.ts
  src/commands/admin/config-reports.ts
  src/commands/admin/config-suggestions.ts
  src/commands/admin/config-welcome.ts
  src/commands/admin/notification-remove.ts
  src/commands/admin/notification-setup.ts
  src/commands/economy/balance.ts
  src/commands/economy/daily.ts
  src/commands/economy/donate.ts
  src/commands/economy/gamble.ts
  src/commands/economy/leaderboard.ts
  src/commands/economy/level.ts
  src/commands/economy/shop.ts
  src/commands/fun/arabfunny.ts
  src/commands/fun/blackjack.ts
  src/commands/fun/crearmeme.ts
  src/commands/fun/fakeyou.ts
  src/commands/fun/frasejoker.ts
  src/commands/fun/imagendura.ts
  src/commands/fun/invertir.ts
  src/commands/fun/kahoot.ts
  src/commands/fun/padalustro.ts
  src/commands/fun/ryangosling.ts
  src/commands/fun/wordle.ts
  src/commands/general/help.ts
  src/commands/general/report.ts
  src/commands/general/server-info.ts
  src/commands/general/suggest.ts
  src/commands/moderation/ban.ts
  src/commands/moderation/kick.ts
  src/commands/moderation/timeout.ts
  src/commands/music/clear.ts
  src/commands/music/loop.ts
  src/commands/music/now-playing.ts
  src/commands/music/pause.ts
  src/commands/music/play.ts
  src/commands/music/previous.ts
  src/commands/music/queue.ts
  src/commands/music/shuffle.ts
  src/commands/music/skip.ts
  src/commands/music/stop.ts
  src/commands/rpg/stats.ts
  src/events/guildMemberAdd/welcomeCard.ts
  src/events/interactionCreate/handleCommands.ts
  src/handlers/commandHandler.ts
  src/handlers/eventHandler.ts
  src/index.ts
  src/lib/deployCommands.ts
  src/lib/types.d.ts
  src/utils/readFiles.ts
  tsconfig.json
Labels: bug, improvement

#46 Mariwano v1.4.0
  Dockerfile
  package-lock.json
  package.json
  src/commands/admin/autorole-configure.ts
  src/commands/admin/autorole-diable.ts
  src/commands/admin/config-reports.ts
  src/commands/admin/config-suggestions.ts
  src/commands/admin/config-welcome.ts
  src/commands/admin/notification-remove.ts
  src/commands/admin/notification-setup.ts
  src/commands/economy/balance.ts
  src/commands/economy/daily.ts
  src/commands/economy/donate.ts
  src/commands/economy/gamble.ts
  src/commands/economy/leaderboard.ts
  src/commands/economy/level.ts
  src/commands/economy/shop.ts
  src/commands/fun/arabfunny.ts
  src/commands/fun/blackjack.ts
  src/commands/fun/crearmeme.ts
  src/commands/fun/fakeyou.ts
  src/commands/fun/frasejoker.ts
  src/commands/fun/imagendura.ts
  src/commands/fun/invertir.ts
  src/commands/fun/kahoot.ts
  src/commands/fun/padalustro.ts
  src/commands/fun/ryangosling.ts
  src/commands/fun/wordle.ts
  src/commands/general/help.ts
  src/commands/general/report.ts
  src/commands/general/server-info.ts
  src/commands/general/suggest.ts
  src/commands/moderation/ban.ts
  src/commands/moderation/kick.ts
  src/commands/moderation/timeout.ts
  src/commands/music/clear.ts
  src/commands/music/loop.ts
  src/commands/music/now-playing.ts
  src/commands/music/pause.ts
  src/commands/music/play.ts
  src/commands/music/previous.ts
  src/commands/music/queue.ts
  src/commands/music/shuffle.ts
  src/commands/music/skip.ts
  src/commands/music/stop.ts
  src/commands/rpg/stats.ts
  src/events/guildMemberAdd/welcomeCard.ts
  src/events/interactionCreate/handleCommands.ts
  src/handlers/commandHandler.ts
  src/handlers/eventHandler.ts
  src/index.ts
  src/lib/deployCommands.ts
  src/lib/types.d.ts
  src/utils/readFiles.ts
  tsconfig.json
Labels: bug, new feature, improvement

#47 Arreglar error a la hora de registrar los comandos
  src/handlers/commandHandler.ts
  src/handlers/eventHandler.ts
  src/index.ts
  src/lib/deployCommands.ts
Labels: bug
